//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP6_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public int Id { get; set; }
        public string text { get; set; }
    
        public virtual Movies Movy { get; set; }
    }
}
