//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP6_BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int Id { get; set; }
        public string original_language { get; set; }
        public string original_title { get; set; }
        public string release_date { get; set; }
        public string vote_avarage { get; set; }
        public string vote_count { get; set; }
        public string overview { get; set; }
        public string popularity { get; set; }
    }s
}
